# Generated by Django 2.2 on 2024-05-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CC', 'Cash Crop'), ('FC', 'Food Crop'), ('LS', 'Livestock')], default='CC', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('D', 'Danger'), ('P', 'Primary'), ('S', 'Secondary')], default='D', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(default='crops', max_length=100),
            preserve_default=False,
        ),
    ]
