# Generated by Django 4.2.11 on 2024-05-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('CC', 'Cash Crops'), ('FC', 'Food Crops'), ('L', 'LiveStock')], max_length=2),
        ),
    ]
